{
	"version": 1758962552,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tumblr_mm55e88n8h1rnir1do1_-sheet0.png",
		"images/indeliblerichguillemotmax1mb-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground6.png",
		"images/tiledbackground7.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/9patch.png",
		"images/b3dparticles.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"v_portalgun_p2to1.png",
		"2025-09-15_09-58-09.png",
		"i (3).png",
		"islands-68.png",
		"3432324.png",
		"портальчик мини.png",
		"портальчик мини (1).png",
		"half-life_2_-_complete_city-17_buildings.glb",
		"аывыавываы.glb",
		"big_soviet_panel_house_lowpoly.glb",
		"low_poly_kids_playground.glb",
		"abandoned_alley_game_ready (1).glb",
		"destroyed_bus_01.glb",
		"old_rusty_car_2.glb",
		"vr_room_light_baked.glb",
		"vr_art_gallery_room.glb",
		"combine_gates__half_life_2_enhanced.glb",
		"babylon.js",
		"babylonjs.loaders.min.js",
		""
	]
}